### ISSUE TITLE
[feat/EPIC-79-login] 로그인 구현

### ISSUE THREAD

**Issue by ibaesuyeon** [STUDIO-EYE/STUDIO-EYE-USER-SERVICE#1]
## 📄 이슈 내용 

기존 코드에서 돌아가지 않는 로그인 기능을 수정하여 정상 작동하도록 합니다.

## ✔ 체크리스트

- [x] 레디스 환경변수 및 코드 수정
- [x] JWT 환경변수 및 코드 수정
- [x] SMTP 환경변수 및 코드 수정
- [x] jasypt 환경변수 및 코드 수정

## 📍 Reference

-
